### PR TITLE
soc_018_missing_migrants

### PR DESCRIPTION
**Pull request by chrowe**
1. Fixing broken nrt script:
    1. The original issue was that the dataset has rows with no coordinates which lead to a `break` statement to be triggered in the loop that processes the dataset row by row. Since the records with no coordinates was at the beginning of the file, it meant none of the new records were being read. This was fixed with 7069daff6487ed17a7704971dab9dbff9f0d149f
    2. That uncovered an issue with rows later in the file that had missing dates which was causing the script to fail, so I added a check for a valid date. ba5b8fbc832f65361e1ccb55601c790ed1756171
    3. Also, the url field is no longer a suable uid, so switched to `Main_ID` bc80e94f2474f54ea4b004c5f9f4e097cc534fac
    4. More recently it seems they started using a 2 digit month in their url instead of 1 digit. That is fixed by 0aac8ab027bfe7cd3a786c1db6490b4585854f78 and 8077dd3b2e5e25dba7ecaa252a7df0adcf624ea1
2. General updates
    1. Update python and package versions 65fde629e25f78a0fee63166eb713bf73741032e
    2. Added some logging messages to make it easier to tell why the script is failing e28ec0c3f883904c2990b74269666350c3ebf8ce

### CODE REVIEW

**Comment by weiqi-tori** [comment]
I reduced the logging info for `Row has no Coordinates`, `Row has no valid date`, and `Row is older than max age` 
([5677fe9](https://github.com/resource-watch/nrt-scripts/pull/1129/commits/6577f9ea760c5c2a3eb906fdf1b0fd00dc4b0b95) ). Because it will print out more than 3000 logging info without clear identification of which record(s) are causing the problem. What do you think? Or we can subset the dataframe by max-age first, before iterating rows.

**Comment by chrowe** [comment]
I think it is useful to have some info in the logs about this. What about creating a counter for each case and just logging the total number of each so we have some idea about how many records are not being added to our dataset?

**Comment by weiqi-tori** [comment]
> I think it is useful to have some info in the logs about this. What about creating a counter for each case and just logging the total number of each so we have some idea about how many records are not being added to our dataset?

Agreed. That's more clear.

**Comment by chrowe** [comment]
Merge this now and I will create a new PR for the logging.

**Review by weiqi-tori — APPROVED** [review]

**Pull request merged**
