### PR TITLE
Feature/cli 037 smoke plumes

### PR DESCRIPTION
**Pull request by nsuberi**
Attention:
* 20171226 data not being read in, even though it is up on FTP. Not able to access that data by typing address into browser search bar either, though: ftp://satepsanone.nesdis.noaa.gov/FIRE/HMS/GIS/hms_smoke20171226.zip.
* uniqueIDs set to be the date of the observation plus the index in the shape file. This assumes that there will be no duplicates in the shape file.

### CODE REVIEW

**Comment by fgassert** [comment]
1. Your time.cron is every minute. Should this be daily or twice daily?
2. Looks like they keep the archive in a subdirectory. Do you want to pull that in? ftp://satepsanone.nesdis.noaa.gov/FIRE/HMS/GIS/
3. You could probably bump up the max rows a bit. I would probably keep it from getting too high tho in case the shapes get complex.

**Comment by nsuberi** [comment]
Updated cron to run twice daily, grabbed data from the archive, increased max rows.

Q: How will this react to updates in their shape file during each day? In order to work correctly, this approach requires that they append new rows to the end of the file. Otherwise, the unique ID filtering will not work correctly.

One possible solution (in case they do not add data in a predictable manner, appending new observations to the end of the shape file) would be to only grab data once daily, and start looking at the previous day (i.e. if today is Dec 30, start looking at data from Dec 29 which should be complete).

Note: There are preliminary files (i.e. hms_smoke20171229.prelim.shp) that we are not looking at currently.

~ Nathan

**Comment by fgassert** [comment]
Hey,
I'm getting an exception on this one:
Traceback (most recent call last): File "main.py", line 3, in <module> src.main() File "/opt/cli_037/src/__init__.py", line 239, in main existing_count = num_new + num_new_from_archive + len(existing_ids) NameError: name 'num_new_from_archive' is not defined

Also:

log level info
update user and group permissions

**Comment by nsuberi** [comment]
Hi F,

I've fixed the log level to info
Added a logic gate for whether to process the archive to resolve that Exception you encountered
Updated permissions w/ groupadd and useradd according to Alicia's example

~ Nathan

**Pull request merged**
