### PR TITLE
Feature/cli 040 mean sea level rise

### PR DESCRIPTION
**Pull request by nsuberi**
Replace request from cli_025 - I used the wrong unique ID previously

Updated according to suggestions from Francis, plus removed dependency on pandas. Removed procedure to upload to S3 while we decide how we'd like to tackle s3 storage of these NRT data sets.

### CODE REVIEW

**Comment by fgassert** [comment]
There's an issue in the cleaning. If I set `MAX_ROWS` to 100, I get `'new_rows' is not defined`

**Comment by nsuberi** [comment]
The problem with new_rows not being defined is resolved.

**Comment by fgassert** [comment]
You have some other edits that got into this branch.

**Comment by nsuberi** [comment]
F, how can I find the other edits that I need to change?

**Comment by fgassert** [comment]
You have some changes in cli_043 and cli_045 in this branch. If these aren't intended you should un-track them with `git rm`

**Comment by nsuberi** [comment]
I've removed cli_043 and cli_045 from the git history, and merged the master with the branch, and still it says there are conflicting files. What's the proper next step?

**Comment by fgassert** [comment]
Sorry I should have told you to remove the excess files with `checkout` rather than `rm`.

**Pull request merged**
